version: "2"
services:
  web:
    build: .
    ports: 
    - "3030:3030"
    command: npm start
    volumes:
    - .:/usr/src/app/
    depends_on: 
    - mongo
  mongo:
    image: mongo
    ports: 
    - "27017:27017"